#!/usr/bin/env bash
# This Script configures a brand new ubuntu machine with the redirection status code "301 Moved Permanently"

apt-get update -y
apt-get install nginx -y

echo "Hello World!" > /var/www/html/index.html
substitute_string="server_name _;\nrewrite ^\/redirect_me http:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4"

sed -i "s/server_name _;/$substitute_string/g" /etc/nginx/sites-enabled/default

service nginx restart
