#!/usr/bin/env bash
# This Configures HAproxy so that it sends traffic to web-01 and web-02
# Disribute requests using roundrobin algorithm

sudo apt-get update -y
sudo apt-get install haproxy -y

# edit config file
config_file=\
"
frontend  ifedi-frontend
        bind *:80
        mode http
        default_backend ifedi-backend
backend ifedi-backend
        balance roundrobin
        server 302511-web-01 100.25.16.58:80 check
        server 302511-web-02 54.237.13.175:80 check
"
echo "$config_file" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
