#!/usr/bin/env bash
# This Script pings an IP address passed as an argument.
# Accepts a string as an argument, displays Usage: 5-is_the_host_on_the_network {IP_ADDRESS} if no argument was passed
# Pings the IP 5 times

if [ $# -eq 1 ]; then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
