#!/usr/bin/env bash
# This script configures nginx on a ubuntu machine

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt install nginx -y
sudo ufw allow 'Nginx HTTP'
sudo service nginx start
sudo service nginx enable
