#!/usr/bin/env bash
# This Script creates a file, displays a text indefintely when receiving a SIGTERM signal, displays a text when receiving a SIGINT signal and deletes th file that was created and terminates itself when receiving SIGQUIT or SIGTERM signals.

file="/var/run/myscript.pid"
if [ ! -e "$file" ]; then
	touch "$file"
fi

echo "$$" > "$file"


trap 'echo "I hate the kill command"; rm "$file"; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while true;
do
	echo "To infinity and beyond"
	sleep 2
done

