#!/usr/bin/env bash
# This Script displays "To infinity and beyond" indefinitely and "I am invicible!!!" when receiving a SIGTERM signal.

while true;
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' 15
done
