#!/usr/bin/env bash
# Script that displays numbers from 1 to 100.
# Requirement:
# Displays FizzBuzz when the number is a multiple of 3 and 5, displays Fizz when the number is a multiple of 3 and Buzz if a number is a multiple of 5.

for i in {1..100};
do
	if ((i % 15 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo "$i"
	fi
done
