#!/usr/bin/env bash
# This Script displays "Best School" 10 times, but on the 9th iteration, displays it with "Hi" on the next line

n=0

while [ $n -lt 10 ];
do
	echo "Best School"
	if [ $n -eq 9 ]; then
		echo "Hi"
	fi
done
