#!/usr/bin/env bash
# This Scripts loops from 1 to 10 and displays "bad luck" for the 4th iteration, "good luck" for the 8th iteration and "Best School" for the other iterations.

n=0
while [ $n -lt 10 ];
do
	if [ $n -eq 3 ]; then
		echo "bad luck"
	elif [ $n -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	n=$((n + 1))
done
