#!/usr/bin/env bash
# This Script that accepts one argument, runs the whoami command under the user passed as an argument.

user=$1

if  ! id "$user" >/dev/null 2>&1; then
	sudo useradd -m -s /bin/bash "$user"
fi

su - "$user" -c "whoami"

