#!/usr/bin/env bash
# This Script creates an RSA key pair.
# Requirements:
# Name of the created private key must be school, Number of bits should be 4096, the passphrase should be betty.

ssh-keygen -b 4096 -f school -N betty
